### PR TITLE
Fix heath bar issue

### PR DESCRIPTION
**Pull request by pascal-koop**
I deleted the class binding because the value never changes and is always false. this leads to a width of w-96 (24rem). with a hardcoded width of w-full (100%) the loading bar aka health bar stays in the frame. 

Edit:  can you explain what the prop "isSmall" does?

### CODE REVIEW

**Comment by HDenizD** [comment]
> I deleted the class binding because the value never changes and is always false. this leads to a width of w-96 (24rem). with a hardcoded width of w-full (100%) the loading bar aka health bar stays in the frame.
> 
> Edit: can you explain what the prop "isSmall" does?

it toggles the bar height between h-10 or h-12. idk why i added that. maybe its not necessary anymore.

**Review by HDenizD — APPROVED** [review]
can confirm, healthbar looks good now. gj

**Comment by pascal-koop** [comment]
I will check the isSmall prop tomorrow in the morning, test it.

**Comment by pascal-koop** [comment]
> > I deleted the class binding because the value never changes and is always false. this leads to a width of w-96 (24rem). with a hardcoded width of w-full (100%) the loading bar aka health bar stays in the frame.
> 
> > 
> 
> > Edit: can you explain what the prop "isSmall" does?
> 
> 
> 
> it toggles the bar height between h-10 or h-12. idk why i added that. maybe its not necessary anymore.

I will check the isSmall prop tomorrow in the morning and test it.

**Pull request merged**
